### ISSUE TITLE
Improve efficiency for small files

### ISSUE THREAD

**Issue by g1mv** [g1mv/density#24]
It takes a certain amount of data for density's algorithms to be running optimally (ratio wise).
Adding an intermediary processing could be interesting before routing data to the bigger and faster algorithms.
It would also enable preparation of the main algorithm's data structures, while ensuring a good compression ratio immediately thus greatly benefiting smaller files.
As a side effect, #10 would be probably unnecessary as the compression process would be instantly efficient.

**Comment by gpnuma** [comment]
![chameleon](https://cloud.githubusercontent.com/assets/3772944/7826818/a2491b9e-041f-11e5-81fd-e3ba0ac880d9.png)

*The enwik7 compression ratio convergence with Density Chameleon*
